mtcars[1]
colnames(mtcars)=c("crb","carbon","")mtcars
mtcars
colnames(mtcars)[3]
dim(mtcars)[2]
length(mtcars)
attach(mtcars)
df
detach(mtcars)
attach(mtcars)
mpg
df=mtcars
mean(mpg)
mean(cyl)
df$carb = NULL
str(df)
sort(mtcars)
sort(mtcars[1,])
df$gear2=df$gear;
sort(mtcars$mpg,decreasing=T)
